# Staging environment values override
replicaCount: 2
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "staging"
  dbHost: "appointment-db-staging"
  dbName: "appointment_db_staging"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-stage-appointment-service
  tag: 097364e1d6b4609c520d6ed7105787eef7467ad7
