# Staging environment values override
replicaCount: 2
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "staging"
  dbHost: "ui-db-staging"
  dbName: "ui_db_staging"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-stage-frontend
  tag: 8e5cc04d41c058eedb8e31ace84e2e570dc5cc9c
