# Staging environment values override
replicaCount: 2
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "staging"
  dbHost: "health-db-staging"
  dbName: "health_db_staging"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-stage-health-service
  tag: b7d631999e889188797d42b9c96993cf05cc3a7e
