# Staging environment values override
replicaCount: 2
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "staging"
  dbHost: "notes-db-staging"
  dbName: "notes_db_staging"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-stage-notes-service
  tag: 43f82e2779b42a8308fe431d464bb45abe4d8cb2
