# Production environment values override
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  environment: "prod"
  dbHost: "alert-db-prod.internal"
  dbName: "alert_db_prod"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-prod-alert-service
  tag: f1bc4a7bbaa43df722dc113ac91e9ed45a3ac9d3
