# Production environment values override
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  environment: "prod"
  dbHost: "health-db-prod.internal"
  dbName: "health_db_prod"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-prod-health-service
  tag: a3e6fb4d67bf6c5e682919b448f17253b8cb4e4d
