# Production environment values override
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  environment: "prod"
  dbHost: "notes-db-prod.internal"
  dbName: "notes_db_prod"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-prod-notes-service
  tag: 8c08ef73d597d972b3ea35c94310548415db6fa5
