# Production environment values override
replicaCount: 3
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  environment: "prod"
  dbHost: "notification-db-prod.internal"
  dbName: "notification_db_prod"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-prod-notification-service
  tag: 1b8808e0c0424e91e3f1a318328fcf9572dd1ef8
