# Dev environment values override
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "dev"
  dbHost: "alert-db-dev"
  dbName: "alert_db_dev"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-dev-alert-service
  tag: "3c9a4290075db821bcf9ced9e1072e994980656a"
