# Dev environment values override
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "dev"
  dbHost: "audit-db-dev"
  dbName: "audit_db_dev"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-dev-audit-service
  tag: "75780a6f4a4932af5b28a7abdab5073c3bedf12b"
