# Dev environment values override
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "dev"
  dbHost: "audit-db-dev"
  dbName: "audit_db_dev"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-dev-audit-service
  tag: "dc6efc1ca1fbba596db3a9ef17b7a9d409e63c84"
