# Dev environment values override
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "dev"
  dbHost: "auth-db-dev"
  dbName: "users_db_dev"
  cognitoUserPoolId: ""
  cognitoClientId: ""
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-dev-auth-service
  tag: "bb8df1bb877dc7220a5f62d47b33f7553064ffec"
