# Dev environment values override
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  environment: "dev"
  dbHost: "reminder-db-dev"
  dbName: "reminder_db_dev"
image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-dev-reminder-service
  tag: "3db82751ee2e570c229b17f6d86184815e08adf0"
