# Dev environment values override
replicaCount: 2

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  environment: "dev"
  dbHost: "report-db-dev"
  dbName: "report_db_dev"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::462355914183:role/elderpinq-dev-s3-reports-role"

image:
  repository: 462355914183.dkr.ecr.us-east-1.amazonaws.com/elderpinq-dev-report-service
  tag: "sha-59635c9"
